kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-app
  namespace: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: aadityaa173/devops-react-app:19
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
